server:
  port: ${SERVER_PORT}

spring:
  application:
    name: coupit-backend

  # Database
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  # JPA
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

# Firebase
firebase:
  config:
    path: firebase-admin-config.json